/**
 * Postgres DDL emitter.
 *
 * Lowers `SchemaModuleIR` to a single `schema.sql` file containing
 * `CREATE TABLE` statements. Decorators on columns are honoured:
 *
 *   @Primary  → PRIMARY KEY
 *   @Unique   → UNIQUE
 *
 * Nullable types (`String?`) drop `NOT NULL`. Other constraints
 * (foreign keys, indexes) are out of scope for the Phase 4 MVP — they
 * can be added later via decorators (e.g. `@References(Users.ID)`).
 */

import type { SchemaModuleIR, TableIR } from "./ir.js";

export interface SchemaFile {
  path: string;
  contents: string;
}

export function emitPostgresDDL(schema: SchemaModuleIR): SchemaFile {
  const tables = schema.tables.map(renderTable).join("\n\n");
  const contents = `-- Auto-generated by Modra emitter.
-- Backend: ${schema.backend}

${tables}
`;
  return { path: "db/schema.sql", contents };
}

function renderTable(t: TableIR): string {
  const cols = t.columns
    .map((c) => {
      const parts: string[] = [c.name, c.sqlType];
      if (c.primary) parts.push("PRIMARY KEY");
      if (c.unique && !c.primary) parts.push("UNIQUE");
      if (c.defaultExpr) parts.push(`DEFAULT ${c.defaultExpr}`);
      return "  " + parts.join(" ");
    })
    .join(",\n");
  return `CREATE TABLE IF NOT EXISTS ${t.name} (
${cols}
);`;
}
