/**
 * Project orchestration.
 *
 * `emitProject(analysis)` runs the lowering pass, fans out to the
 * frontend / backend / schema / bridge emitters, and returns the full
 * set of files ready to write to disk. It also produces project-level
 * scaffolding (`package.json`, `vite.config.ts`, `tsconfig.json`,
 * `.env.example`, `README.md`).
 */

import type { AnalysisResult } from "../semantic/index.js";
import { emitBridge } from "./bridge.js";
import { lower, type ProjectIR } from "./ir.js";
import { emitNode } from "./node.js";
import { emitPostgresDDL } from "./postgres.js";
import { emitReact } from "./react.js";

export interface ProjectFile {
  path: string;
  contents: string;
}

export interface ProjectEmission {
  ir: ProjectIR;
  files: ProjectFile[];
}

export function emitProject(analysis: AnalysisResult): ProjectEmission {
  const ir = lower(analysis);
  const files: ProjectFile[] = [];

  for (const f of emitReact(ir.client, ir.bridge)) files.push(f);
  for (const f of emitNode(ir.server, ir.schema)) files.push(f);
  files.push(emitPostgresDDL(ir.schema));
  for (const f of emitBridge(ir.bridge, ir.schema)) files.push(f);

  // Scaffolding
  files.push({
    path: "package.json",
    contents: packageJson(ir.name),
  });
  files.push({ path: "vite.config.ts", contents: viteConfig() });
  files.push({ path: "tsconfig.json", contents: tsconfigJson() });
  files.push({ path: ".env.example", contents: envExample() });
  files.push({ path: "README.md", contents: readme(ir.name) });

  return { ir, files };
}

function packageJson(name: string): string {
  return `{
  "name": "${name.toLowerCase()}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev:client": "vite",
    "dev:server": "tsx watch server/index.ts",
    "build": "tsc -b && vite build",
    "preview": "vite preview",
    "start": "node --loader tsx server/index.ts"
  },
  "dependencies": {
    "express": "^4.19.2",
    "pg": "^8.11.5",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@types/express": "^4.17.21",
    "@types/node": "^20.11.30",
    "@types/pg": "^8.11.6",
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@vitejs/plugin-react": "^4.2.1",
    "tsx": "^4.7.1",
    "typescript": "^5.4.3",
    "vite": "^5.2.6"
  }
}
`;
}

function viteConfig(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      "/api": "http://localhost:3000",
    },
  },
});
`;
}

function tsconfigJson(): string {
  return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "jsx": "react-jsx",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "allowImportingTsExtensions": false,
    "verbatimModuleSyntax": false,
    "noEmit": true,
    "isolatedModules": true,
    "allowSyntheticDefaultImports": true
  },
  "include": ["src", "server", "shared"]
}
`;
}

function envExample(): string {
  return `# Postgres connection used by the server.
DATABASE_URL=postgres://postgres:postgres@localhost:5432/modra

# Server port (defaults to 3000).
PORT=3000
`;
}

function readme(name: string): string {
  return `# ${name}

Auto-generated by **Modra**. To run locally:

1. Apply the database schema:

   \`\`\`bash
   psql "$DATABASE_URL" -f db/schema.sql
   \`\`\`

2. Install dependencies:

   \`\`\`bash
   npm install
   \`\`\`

3. Start the backend (Express):

   \`\`\`bash
   npm run dev:server
   \`\`\`

4. In another terminal, start the frontend (Vite + React):

   \`\`\`bash
   npm run dev:client
   \`\`\`

Open <http://localhost:5173>.

> Generated from a single \`${name}.modra\` source file. Edit the
> \`.modra\` file and re-run \`modra build\` to regenerate this app.
`;
}
